"""
Tests for the Apple-tuned regex extractors. These are NOT in the live pipeline
(run() uses XBRL via facts.py) — kept here so the fallback behavior stays pinned.
"""
import math

import pytest

from backend.data_extract import text_metrics


class TestParseNumber:
    def test_success_commas_and_decimals(self):
        assert text_metrics._parse_number("391,035") == 391035.0
        assert text_metrics._parse_number("7.46") == 7.46

    def test_failure_non_numeric_returns_none(self):
        # Junk no longer raises — it returns None so one bad token can't crash a run.
        assert text_metrics._parse_number("not-a-number") is None
        assert text_metrics._parse_number("") is None
        assert text_metrics._parse_number(",") is None

    def test_edge_infinity_parses_to_inf(self):
        assert math.isinf(text_metrics._parse_number("inf"))


class TestSearch:
    def test_success_returns_first_group(self):
        assert text_metrics._search(r"Net income \$ ([\d,]+)",
                                    "Net income $ 93,736") == "93,736"

    def test_failure_no_match_returns_none(self):
        assert text_metrics._search(r"Revenue ([\d,]+)", "nothing here") is None


class TestIncomeStatementRegex:
    def test_success_extracts_revenue_and_income(self):
        out = text_metrics.extract_income_statement(
            "Total net sales $ 391,035\nNet income $ 93,736")
        assert out["total_revenue_millions"] == 391035.0
        assert out["net_income_millions"] == 93736.0

    def test_failure_no_matches_returns_empty(self):
        assert text_metrics.extract_income_statement("irrelevant prose") == {}

    def test_edge_empty_string(self):
        assert text_metrics.extract_income_statement("") == {}


class TestBalanceSheetRegex:
    def test_success_negative_working_capital(self):
        out = text_metrics.extract_balance_sheet(
            "Total current assets $ 152,987\n"
            "Total current liabilities $ 176,392\n"
            "Total assets $ 364,980")
        assert out["total_assets_millions"] == 364980.0
        assert out["working_capital_millions"] == 152987.0 - 176392.0


class TestCashFlowRegex:
    def test_success_free_cash_flow_computed(self):
        out = text_metrics.extract_cash_flow(
            "Cash generated by operating activities $ 118,254\n"
            "Payments for acquisition of property $ 9,447")
        assert out["operating_cash_flow_millions"] == 118254.0
        assert out["capex_millions"] == 9447.0
        assert out["free_cash_flow_millions"] == 118254.0 - 9447.0


class TestQualitative:
    def test_success_themes_macros_employees(self):
        secs = {
            "mda": "Inflation and supply chain pressures persist into next year.",
            "risk_factors": "We face intense competition and cybersecurity risk incl. data breach.",
            "business": "We employed 150,000 full-time equivalent employees.",
        }
        out = text_metrics.extract_qualitative(secs)
        assert "inflation" in out["macro_risks_mentioned"]
        assert "competition" in out["key_risk_themes"]
        assert "cybersecurity" in out["key_risk_themes"]
        assert out["full_time_employees"] == 150000.0

    def test_edge_empty_sections(self):
        out = text_metrics.extract_qualitative({})
        assert out["macro_risks_mentioned"] == []
        assert out["key_risk_themes"] == []

    def test_edge_junk_segment_value_does_not_crash(self):
        # A stray comma where a number should be must not crash; it's skipped,
        # while a valid sibling value still comes through. (Regression for the
        # "could not convert string to float: ''" run failure.)
        out = text_metrics.extract_qualitative(
            {"mda": "Americas $ , and Europe $ 111,032"})
        assert out.get("segment_revenue", {}).get("Europe") == 111032.0
